version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sharedservices-integration1-idpersist:1:1,kafka.topic.ingest=sharedservices-integration1-ingest:1:1,kafka.topic.validated=sharedservices-integration1-validatedIngest:1:1,kafka.topic.allocate=sharedservices-integration1-idallocate:1:1,sharedservices-integration1-idresolved:1:1,object.upsert.kafka.topic=sharedservices-integration1-process:1:1,kafka.topic.process=sharedservices-integration1-process:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
